### ISSUE TITLE
`Tables not found in selected database` while running `npm run entity` 

### ISSUE THREAD

**Issue by wayou** [CatsMiaow/node-nestjs-structure#4]
```sh
$ npm run entity                                                                  15:08:59

> node-nestjs-structure@0.0.0 entity ~/node-nestjs-structure
> node bin/entity

✔ Please enter a database name. … dbname1
✔ Choose whether to proceed with the build. … yes
typeorm-model-generator@0.4.2
[3:09:58 PM] Starting creation of model classes.
Tables not found in selected database. Skipping creation of typeorm model.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.2  node@v14.0.0
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
[3:09:58 PM] Typeorm model classes created.
```

**Comment by CatsMiaow** [comment]
This source does not automatically create databases and tables.
The [entity folder](https://github.com/CatsMiaow/node-nestjs-structure/tree/master/src/entity) is a sample file.

Enter the name of the database that created the table yourself.
You can also use TypeORM's synchronize option in [development.ts](https://github.com/CatsMiaow/node-nestjs-structure/blob/master/src/config/development.ts)

https://typeorm.io/#/connection-options
> synchronize - Indicates if database schema should be auto created on every application launch. Be careful with this option and don't use this in production - otherwise you can lose production data. This option is useful during debug and development. As an alternative to it, you can use CLI and run schema:sync command. Note that for MongoDB database it does not create schema, because MongoDB is schemaless. Instead, it syncs just by creating indices.

**Comment by wayou** [comment]
Thanks for the reply.

And any clue about this?

```sh
$ npm run start:dev

> node-nestjs-structure@0.0.0 start:dev ~/node-nestjs-structure
> nest start --watch
[5:24:08 PM] Starting compilation in watch mode...

src/sample/controllers/sample.controller.ts:7:28 - error TS6305: Output file '~/node-nestjs-structure/dist/entity/dbname1/index.d.ts' has not been built from source file '~/node-nestjs-structure/src/entity/dbname1/index.ts'.

7 import { Tablename1 } from '../../entity/dbname1';
                             ~~~~~~~~~~~~~~~~~~~~~~
...
```

**Comment by CatsMiaow** [comment]
First you need to build the entity.
```sh
npm ci
npm run build:entity
npm run start:dev
```
https://github.com/CatsMiaow/node-nestjs-structure/commit/fa155587cedbce921297617a06619d77c27c4216 Fixed README. Thank you.
