### ISSUE TITLE
using jest without -i in this project create issue

### ISSUE THREAD

**Issue by alokdeshwal-st** [CatsMiaow/node-nestjs-structure#6]
Me too using multiple files for test cases with jest but without -i parameter. Because -i as per jest documentation is discouraged due to in-efficient in case we have too many files which will be executed in sequence only if being used with -i parameter with jest.

is there any work-around for that?

**Comment by CatsMiaow** [comment]
The repository code is just an example, you can remove it depending on your situation.
https://jestjs.io/docs/cli#--runinband
> Alias: `-i`. Run all tests serially in the current process, rather than creating a worker pool of child processes that run tests. This can be useful for debugging.

https://stackoverflow.com/questions/43864793/why-does-jest-runinband-speed-up-tests
As you said, it's inefficient for many tests, but can be fast for smaller tests as it doesn't cost a child process.
