### ISSUE TITLE
envFilePath in ConfigModule

### ISSUE THREAD

**Issue by AndyJYK** [CatsMiaow/node-nestjs-structure#7]
Thanks for sharing this structure. This is the best nestjs boilerplate that I've ever used!
I have 1 question though, is it okay to drop envFilePath in **ConfigModule.forRoot({ ... })** ?
Cause I can't access to env variant without declaring envFilePath 

```
ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: process.env.NODE_ENV === 'dev' ? '.env.dev' : '.env.test',    // if not, can't access to env
      load: [configuration]
    }),
```

**Comment by CatsMiaow** [comment]
If you want to load a different `.env` file for each environment, it is correct to add the `envFilePath` option as you wrote.

https://docs.nestjs.com/techniques/configuration#custom-env-file-path
> By default, the package looks for a `.env` file in the root directory of the application. To specify another path for the `.env` file, set the `envFilePath` property of an (optional) options object you pass to `forRoot()`
